<?php

namespace App\Foo;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-20 at 14:52:19.
 */
class FizzBuzzTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var FizzBuzz
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FizzBuzz;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers App\Foo\FizzBuzz::check
     * @todo   Implement testCheck().
     */
    public function testCheck()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \App\Foo\FizzBuzz::check
     */
    public function testGetFizz()
    {
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \App\Foo\FizzBuzz::check
     */
    public function testGetBuzz()
    {
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \App\Foo\FizzBuzz::check
     */
    public function testGetFizzBuzz()
    {
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \App\Foo\FizzBuzz::check
     */
    public function testGetPassThru()
    {
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
